### ISSUE TITLE
Segmentation fault due to missing schema migration

### ISSUE THREAD

**Issue by ghost** [adamreichold/QMediathekView#4]
Hi, on Arch Linux I'm using the AUR package qmediathekview-git and am getting segfaults. I cannot exactly state when this started to show, it's been a while since I used the app.

$ lsb_release -d
Description:	Arch Linux

$ pacman -Qi qmediathekview-git | grep Version
Version         : r53.21c0213-1

$ pacman -Qi qt5-base | grep Version
Version         : 5.7.0-3

$ QMediathekView
QSqlError("1", "Unable to execute statement", "no such column: key")
Segmentation fault (core dumped)

$ journalctl | grep QMediathekView
Nov 05 06:17:07 lab16 kernel: QMediathekView[24395]: segfault at 10 ip 00007ff5138ac0bb sp 00007ffe0eda9c50 error 4 in libQt5Sql.so.5.7.0[7ff51389a000+46000]
Nov 05 06:17:52 lab16 kernel: QMediathekView[24545]: segfault at 10 ip 00007f6133ca40bb sp 00007ffce07ed910 error 4 in libQt5Sql.so.5.7.0[7f6133c92000+46000]
Nov 05 06:40:30 lab16 kernel: QMediathekView[31400]: segfault at 10 ip 00007f50b77e20bb sp 00007ffeb8435a70 error 4 in libQt5Sql.so.5.7.0[7f50b77d0000+46000]

Regards

**Comment by adamreichold** [comment]
Hello,

since there never really was a public release of this software, it does not yet implement migration of the internal database schema and the crash looks like a current version of the program trying to work with a database created by an older version.

You should be able to fix this by deleting `~/.local/share/QMediathekView/QMediathekView/database` and probably removing the line beginning with `databaseUpdatedOn=` from `~/.config/QMediathekView/QMediathekView.conf`.

Of course, a real fix will be to implement schema migration using SQLite's user version property to drop old tables and indexes if necessary, but I am not sure if I am willing to commit to do this as part of this bug report...

**Comment by ghost** [comment]
Thanks for clearing things up so rapidly. After making the suggested changes everything started working. And it works really well, much more responsive searching compared to the java version. Regarding implementing schema migration I fully understand your argument. I took the liberty to add a comment at the AUR pointing here for any users that might face similar issues.

**Comment by adamreichold** [comment]
I just pushed a rather roundabout way of doing "schema migration": The program will check user version and just delete the whole database file if the schema version does not match the program version. After that, the new database will be repopulated by a full list fetch and import. This should resolve such problems without inducing a maintenance burden to actually convert the schema content...

**Comment by ghost** [comment]
Nice you've found a solution that suits you. Thanks for taking the time and doing the work. As this is fixed I've removed the AUR comment.

Regards and all the best with this project.
