### ISSUE TITLE
distribution-via-torrent branch

### ISSUE THREAD

**Issue by probonopd** [adamreichold/QMediathekView#8]
The distribution-via-torrent branch sounds intriguing. Is this still being developed?
May help against the nonsense "[depublication](https://de.wikipedia.org/wiki/Depublizieren)".

**Comment by adamreichold** [comment]
I proposed this in the MediathekView forums when the original author threatened to stop the project due to the high costs of hosting the database snapshots. That particular branch was a proof of concept to demonstrate how this could work using a local BitTorrent tracker. But the idea was eventually shot down as people just donated bandwidth instead. (The main concern with P2P approaches was the trouble setting up typical consumer routers with the necessary port forwarding and such IIRC.)

**Comment by probonopd** [comment]
I was (mis)reading it as auto-seeding the payload video files...
